source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '11.0'

target 'AJUIKit_Example' do
  pod 'AJUIKit', :path => '../'

  target 'AJUIKit_Tests' do
    inherit! :search_paths

    
  end
end
